export MOD=fxtec_qx1000
export NDS_GCC=0
export NDS_ALSA=1

CFLAGS  += -O3
CFLAGS  += -DFXTEC_QX1000
CFLAGS  += -Wl,--no-undefined

CFLAGS  += -mfpu=neon
CFLAGS  += -ffast-math
CFLAGS  += -march=armv7-a
CFLAGS  += -mtune=cortex-a7

LDFLAGS += -lpulse
LDFLAGS += -ljson-c

export MORE_CFLAGS=${CFLAGS}
export MORE_LDFLAGS=${LDFLAGS}

include Makefile.base

.PHONY: cp
cp:
	cp -a drastic/lib/* ~/Game/qx1000/nds/lib/
