export MOD=qx1000
export HOST=arm-linux
    
$(shell cd sdl2 && rm -rf libEGL.so libGLESv2.so)

SDL2_CFG+= --enable-loadso
SDL2_CFG+= --enable-joystick
SDL2_CFG+= --disable-video-opengl
SDL2_CFG+= --disable-video-opengles
SDL2_CFG+= --disable-video-opengles2

include Makefile.mk
