export MOD=ut
export NDS_GCC=0
export NDS_ALSA=1

CFLAGS  = -DUT
CFLAGS  += -I../ut/src
CFLAGS  += -I../ut/extras/memory/src
CFLAGS  += -I../ut/extras/fixture/src
CFLAGS  += -fsanitize=leak
CFLAGS  += -fsanitize=address
CFLAGS  += -ggdb
CFLAGS  += -I../inc/mini

LDFLAGS += -lasan
LDFLAGS += -lubsan
LDFLAGS += -lpulse
LDFLAGS += -ljson-c

export MORE_CFLAGS=${CFLAGS}
export MORE_LDFLAGS=${LDFLAGS}

include Makefile.base
