export MOD=qx1000
export NDS_GCC=0
export NDS_ALSA=1

CFLAGS  += -O3
CFLAGS  += -DQX1000
CFLAGS  += -Wl,--no-undefined

CFLAGS  += -mfpu=neon
CFLAGS  += -ffast-math
CFLAGS  += -march=armv7-a
CFLAGS  += -mtune=cortex-a7

LDFLAGS += -lpulse
LDFLAGS += -ljson-c

export MORE_CFLAGS=${CFLAGS}
export MORE_LDFLAGS=${LDFLAGS}

include Makefile.mk
