export MOD=pandora
export NDS_GCC=0
export NDS_ALSA=1

CFLAGS  += -O3
CFLAGS  += -DPANDORA
CFLAGS  += -Wl,--no-undefined

CFLAGS  += -mfpu=neon
CFLAGS  += -ffast-math
CFLAGS  += -march=armv7-a
CFLAGS  += -mtune=cortex-a8
CFLAGS  += -ftree-vectorize
CFLAGS  += -mfloat-abi=softfp

LDFLAGS += -ljson-c
 
export MORE_CFLAGS=${CFLAGS}
export MORE_LDFLAGS=${LDFLAGS}

include Makefile.mk
