export MOD=flip
export NDS_GCC=1
export NDS_ALSA=0

CFLAGS += -O3
CFLAGS += -DFLIP
CFLAGS  += -Wl,--no-undefined

CFLAGS  += -mfpu=neon
CFLAGS  += -ffast-math
CFLAGS  += -march=armv7-a
CFLAGS  += -mtune=cortex-a7

LDFLAGS+= -ljson-c
 
export MORE_CFLAGS=${CFLAGS}
export MORE_LDFLAGS=${LDFLAGS}

include Makefile.mk

.PHONY: push
push:
	adb push drastic/lib/* /mnt/sdcard/Emu/drastic/lib/
