export MOD=rg28xx
export PATH=/opt/a30/bin:$(shell echo $$PATH)
export CROSS=/opt/a30/bin/arm-linux-
export CC=${CROSS}gcc
export AR=${CROSS}ar
export AS=${CROSS}as
export LD=${CROSS}ld
export CXX=${CROSS}g++
export HOST=arm-linux
    
$(shell cd sdl2 && rm -rf libEGL.so libGLESv2.so)

SDL2_CFG+= --enable-loadso
SDL2_CFG+= --enable-joystick
SDL2_CFG+= --disable-video-opengl
SDL2_CFG+= --disable-video-opengles
SDL2_CFG+= --disable-video-opengles2

include Makefile.mk
