export MOD=xt897
export NDS_GCC=0
export NDS_ALSA=1

CFLAGS  += -O3
CFLAGS  += -DXT897
CFLAGS  += -Wl,--no-undefined

CFLAGS  += -mfpu=neon
CFLAGS  += -ffast-math
CFLAGS  += -march=armv7-a
CFLAGS  += -mtune=cortex-a7

LDFLAGS += -lpulse
LDFLAGS += -ljson-c

export MORE_CFLAGS=${CFLAGS}
export MORE_LDFLAGS=${LDFLAGS}

include Makefile.mk

.PHONY: cp
cp:
	cp -a drastic/lib/* ~/Game/xt897/nds/lib/
	cp -a drastic/res/shader/* ~/Game/xt897/nds/res/shader/
