export MOD=ut
export NDS_GCC=0
export NDS_ALSA=1

CFLAGS  = -DUT
CFLAGS += -I../ut/src
CFLAGS += -I../ut/extras/fixture/src
CFLAGS += -I../ut/extras/memory/src

export MORE_CFLAGS=${CFLAGS}

include Makefile.mk
