#include "unity_fixture.h"
TEST_GROUP_RUNNER(util)
{
}
TEST_GROUP_RUNNER(detour)
{
RUN_TEST_CASE(detour, unlock_protected_area)
RUN_TEST_CASE(detour, fast_forward)
RUN_TEST_CASE(detour, prehook_cb_load_state_index)
RUN_TEST_CASE(detour, prehook_cb_save_state_index)
RUN_TEST_CASE(detour, prehook_cb_initialize_backup)
RUN_TEST_CASE(detour, save_state)
RUN_TEST_CASE(detour, load_state)
RUN_TEST_CASE(detour, quit_drastic)
RUN_TEST_CASE(detour, add_prehook_cb)
RUN_TEST_CASE(detour, write_file)
RUN_TEST_CASE(detour, drop_bios_files)
RUN_TEST_CASE(detour, init_table)
RUN_TEST_CASE(detour, init_hook)
RUN_TEST_CASE(detour, quit_hook)
RUN_TEST_CASE(detour, render_polygon_setup_perspective_steps)
}
TEST_GROUP_RUNNER(alsa)
{
RUN_TEST_CASE(alsa, adpcm_decode_block)
RUN_TEST_CASE(alsa, context_state_cb)
RUN_TEST_CASE(alsa, stream_state_cb)
RUN_TEST_CASE(alsa, stream_latency_update_cb)
RUN_TEST_CASE(alsa, stream_request_cb)
RUN_TEST_CASE(alsa, snd_lib_error_set_handler)
RUN_TEST_CASE(alsa, set_mini_vol_raw)
RUN_TEST_CASE(alsa, set_mini_vol)
RUN_TEST_CASE(alsa, inc_mini_vol)
RUN_TEST_CASE(alsa, dec_mini_vol)
RUN_TEST_CASE(alsa, inc_a30_vol)
RUN_TEST_CASE(alsa, dec_a30_vol)
RUN_TEST_CASE(alsa, open_dsp)
RUN_TEST_CASE(alsa, set_half_vol)
RUN_TEST_CASE(alsa, set_auto_state)
RUN_TEST_CASE(alsa, init_queue)
RUN_TEST_CASE(alsa, quit_queue)
RUN_TEST_CASE(alsa, get_available_rsize)
RUN_TEST_CASE(alsa, get_available_wsize)
RUN_TEST_CASE(alsa, put_queue)
RUN_TEST_CASE(alsa, get_queue)
RUN_TEST_CASE(alsa, audio_handler)
RUN_TEST_CASE(alsa, snd_pcm_avail)
RUN_TEST_CASE(alsa, snd_pcm_hw_params)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_any)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_free)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_malloc)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_set_access)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_set_buffer_size_near)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_set_channels)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_set_format)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_set_period_size_near)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_set_rate_near)
RUN_TEST_CASE(alsa, snd_pcm_open)
RUN_TEST_CASE(alsa, snd_pcm_prepare)
RUN_TEST_CASE(alsa, snd_pcm_readi)
RUN_TEST_CASE(alsa, snd_pcm_recover)
RUN_TEST_CASE(alsa, snd_pcm_start)
RUN_TEST_CASE(alsa, snd_pcm_close)
RUN_TEST_CASE(alsa, snd_pcm_sw_params)
RUN_TEST_CASE(alsa, snd_pcm_sw_params_current)
RUN_TEST_CASE(alsa, snd_pcm_sw_params_free)
RUN_TEST_CASE(alsa, snd_pcm_sw_params_malloc)
RUN_TEST_CASE(alsa, snd_pcm_writei)
}
TEST_GROUP_RUNNER(sdl2_video)
{
RUN_TEST_CASE(sdl2_video, sigterm_handler)
}
TEST_GROUP_RUNNER(sdl2_joystick)
{
RUN_TEST_CASE(sdl2_joystick, open_uart)
RUN_TEST_CASE(sdl2_joystick, set_uart)
RUN_TEST_CASE(sdl2_joystick, init_uart)
RUN_TEST_CASE(sdl2_joystick, read_uart)
RUN_TEST_CASE(sdl2_joystick, filter_dead_zone)
RUN_TEST_CASE(sdl2_joystick, limit_value)
RUN_TEST_CASE(sdl2_joystick, update_axis_values)
RUN_TEST_CASE(sdl2_joystick, frame_to_axis)
RUN_TEST_CASE(sdl2_joystick, parse_serial_buf)
RUN_TEST_CASE(sdl2_joystick, init_serial)
RUN_TEST_CASE(sdl2_joystick, read_joy_cfg)
RUN_TEST_CASE(sdl2_joystick, joy_handler)
RUN_TEST_CASE(sdl2_joystick, JoystickInit)
RUN_TEST_CASE(sdl2_joystick, JoystickQuit)
RUN_TEST_CASE(sdl2_joystick, JoystickGetCount)
RUN_TEST_CASE(sdl2_joystick, JoystickDetect)
RUN_TEST_CASE(sdl2_joystick, JoystickGetDeviceName)
RUN_TEST_CASE(sdl2_joystick, JoystickGetDevicePlayerIndex)
RUN_TEST_CASE(sdl2_joystick, JoystickSetDevicePlayerIndex)
RUN_TEST_CASE(sdl2_joystick, JoystickGetDeviceGUID)
RUN_TEST_CASE(sdl2_joystick, JoystickGetDeviceInstanceID)
RUN_TEST_CASE(sdl2_joystick, JoystickOpen)
RUN_TEST_CASE(sdl2_joystick, JoystickClose)
RUN_TEST_CASE(sdl2_joystick, JoystickRumble)
RUN_TEST_CASE(sdl2_joystick, JoystickRumbleTriggers)
RUN_TEST_CASE(sdl2_joystick, JoystickGetCapabilities)
RUN_TEST_CASE(sdl2_joystick, JoystickSetLED)
RUN_TEST_CASE(sdl2_joystick, JoystickSendEffect)
RUN_TEST_CASE(sdl2_joystick, JoystickSetSensorsEnabled)
RUN_TEST_CASE(sdl2_joystick, JoystickUpdate)
RUN_TEST_CASE(sdl2_joystick, JoystickGetGamepadMapping)
}
TEST_GROUP_RUNNER(sdl2_render)
{
RUN_TEST_CASE(sdl2_render, window_event)
RUN_TEST_CASE(sdl2_render, create_texture)
RUN_TEST_CASE(sdl2_render, lock_texture)
RUN_TEST_CASE(sdl2_render, update_texture)
RUN_TEST_CASE(sdl2_render, unlock_texture)
RUN_TEST_CASE(sdl2_render, set_texture_scale_mode)
RUN_TEST_CASE(sdl2_render, set_render_target)
RUN_TEST_CASE(sdl2_render, queue_set_viewport)
RUN_TEST_CASE(sdl2_render, queue_draw_points)
RUN_TEST_CASE(sdl2_render, queue_fill_rects)
RUN_TEST_CASE(sdl2_render, queue_copy)
RUN_TEST_CASE(sdl2_render, run_command_queue)
RUN_TEST_CASE(sdl2_render, render_read_pixels)
RUN_TEST_CASE(sdl2_render, render_present)
RUN_TEST_CASE(sdl2_render, destroy_texture)
RUN_TEST_CASE(sdl2_render, destroy_renderer)
RUN_TEST_CASE(sdl2_render, set_vsync)
RUN_TEST_CASE(sdl2_render, create_renderer)
}
