#include "unity_fixture.h"
TEST_GROUP_RUNNER(sdl2_video)
{
RUN_TEST_CASE(sdl2_video, sigterm_handler)
}
TEST_GROUP_RUNNER(detour)
{
RUN_TEST_CASE(detour, unlock_protected_area)
RUN_TEST_CASE(detour, fast_forward)
RUN_TEST_CASE(detour, prehook_cb_load_state_index)
RUN_TEST_CASE(detour, prehook_cb_save_state_index)
RUN_TEST_CASE(detour, prehook_cb_initialize_backup)
RUN_TEST_CASE(detour, save_state)
RUN_TEST_CASE(detour, load_state)
RUN_TEST_CASE(detour, quit_drastic)
RUN_TEST_CASE(detour, add_prehook_cb)
RUN_TEST_CASE(detour, write_file)
RUN_TEST_CASE(detour, drop_bios_files)
RUN_TEST_CASE(detour, init_hook)
RUN_TEST_CASE(detour, quit_hook)
RUN_TEST_CASE(detour, render_polygon_setup_perspective_steps)
}
TEST_GROUP_RUNNER(alsa)
{
RUN_TEST_CASE(alsa, init_queue)
RUN_TEST_CASE(alsa, quit_queue)
RUN_TEST_CASE(alsa, get_available_rsize)
RUN_TEST_CASE(alsa, get_available_wsize)
RUN_TEST_CASE(alsa, put_queue)
RUN_TEST_CASE(alsa, get_queue)
RUN_TEST_CASE(alsa, audio_handler)
RUN_TEST_CASE(alsa, snd_pcm_avail)
RUN_TEST_CASE(alsa, snd_pcm_hw_params)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_any)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_free)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_malloc)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_set_access)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_set_buffer_size_near)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_set_channels)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_set_format)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_set_period_size_near)
RUN_TEST_CASE(alsa, snd_pcm_hw_params_set_rate_near)
RUN_TEST_CASE(alsa, snd_pcm_open)
RUN_TEST_CASE(alsa, snd_pcm_prepare)
RUN_TEST_CASE(alsa, snd_pcm_readi)
RUN_TEST_CASE(alsa, snd_pcm_recover)
RUN_TEST_CASE(alsa, snd_pcm_start)
RUN_TEST_CASE(alsa, snd_pcm_close)
RUN_TEST_CASE(alsa, snd_pcm_sw_params)
RUN_TEST_CASE(alsa, snd_pcm_sw_params_current)
RUN_TEST_CASE(alsa, snd_pcm_sw_params_free)
RUN_TEST_CASE(alsa, snd_pcm_sw_params_malloc)
RUN_TEST_CASE(alsa, snd_pcm_writei)
}
