all: box86
	gcc hello.c -o hello -m32
	gcc main.c libbox86.so -o test -I../src -I../src/include -m32 -lm && LD_LIBRARY_PATH=. ./test hello

box86:
ifeq ($(wildcard ../build/libbox86.so),)
	cd .. && ./build.sh x86
else
	cd ../build && make
endif

clean:
	rm -rf test hello
